# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration


client_id = "d67f964108133fc2d33bf22f73a714e0"
name = "product-manager"
application_url = "https://example.com"
embedded = true

[webhooks]
api_version = "2026-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_metaobject_definitions,write_metaobjects,write_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[build]

automatically_update_urls_on_dev = true
